// desktop/src/plugins/nut/users/Logs.vue
<template>
<dashboard-layout :title="title" :role="null" :init="init">
  <el-pagination @current-change="setPage" :page-size="size" layout="total, prev, pager, next" :total="items.length" />
  <el-table :data="table" border>
    <el-table-column prop="createdAt" :label="$t('attributes.created-at')" width="240">
      <template slot-scope="scope">
        <timestamp :value="scope.row.createdAt"/>
      </template>
    </el-table-column>
    <el-table-column prop="ip" :label="$t('attributes.ip')" width="180" />
    <el-table-column prop="message" :label="$t('attributes.content')" />
  </el-table>
</dashboard-layout>
</template>

<script>
import {
  client,
  failed
} from '@/request'
import lodash from 'lodash'

export default {
  name: 'UsersLogs',
  data() {
    return {
      title: this.$t("nut.users.logs.title"),
      size: 12,
      page: 1,
      items: []
    }
  },
  computed: {
    table() {
      var offset = (this.page - 1) * this.size;
      return lodash(this.items).slice(offset).take(this.size).value()
    }
  },
  methods: {
    init() {
      client().request(`query logs{
        listUserLog {
          id,
          ip,
          message,
          createdAt
        }
      }`, {}).then((rst) => {
        this.items = rst.listUserLog
      }).catch(failed)
    },
    setPage(p) {
      this.page = p
    }
  }
}
</script>

// dashboard/src/pages/users/logs.jsx
import React, {
  Component
} from 'react'
import {
  FormattedMessage
} from 'react-intl'

import Layout from "../../components/layouts/Table"
import Authorized from '../../components/Authorized'
import {
  failed,
  client
} from '../../utils/request'
import {
  show as moment
} from '../../utils/moment'
import {
  is_sign_in
} from '../../utils/authorized'


class Widget extends Component {
  constructor(props) {
    super(props)
    this.state = {
      items: [],
      columns: [{
        title: (<FormattedMessage id="attributes.created-at"/>),
        render: (text, record) => moment(record.createdAt),
        width: 280,
        key: 'createdAt'
      }, {
        title: (<FormattedMessage id="attributes.ip"/>),
        dataIndex: 'ip',
        width: 150,
        key: 'ip'
      }, {
        title: (<FormattedMessage id="attributes.content"/>),
        dataIndex: 'message',
        key: 'message'
      }]
    }
  }
  componentDidMount() {
    client().request(`query logs{
        listUserLog {
          id,
          ip,
          message,
          createdAt
        }
      }`, {}).then((rst) => {
      this.setState({
        items: rst.listUserLog
      })
    }).catch(failed)
  }
  render() {
    const {
      items,
      columns
    } = this.state
    return (<Authorized check={is_sign_in}>
      <Layout title={{
        id: "nut.users.logs.title"
      }} items={items} columns={columns}/>
    </Authorized>)
  }
}

export default Widget;
