// desktop/src/plugins/nut/users/SignIn.vue
<template>
<application-layout :title="title">
  <el-card :header="title">
    <el-form :rules="rules" ref="form" :model="form" label-width="80px">
      <el-form-item :label="$t('attributes.email')" prop="email">
        <el-input v-model="form.email" clearable required/>
      </el-form-item>
      <el-form-item :label="$t('attributes.password')" prop="password">
        <el-input type="password" v-model="form.password" clearable auto-complete="off" />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="submitForm('form')">{{$t('buttons.submit')}}</el-button>
        <el-button @click="resetForm('form')">{{$t('buttons.reset')}}</el-button>
      </el-form-item>
    </el-form>
    <shared-links />
  </el-card>
</application-layout>
</template>

<script>
import SharedLinks from './SharedLinks'
import {
  client,
  failed
} from '@/request'

export default {
  name: 'UsersSignIn',
  components: {
    'shared-links': SharedLinks
  },
  data() {
    return {
      title: this.$t('nut.users.sign-in.title'),
      form: {
        name: '',
        password: ''
      },
      rules: {
        email: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }, {
          type: 'email',
          message: this.$t('validations.email'),
          trigger: ['blur', 'change']
        }],
        password: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }]
      }
    }
  },
  methods: {
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          client().request(`mutation form($email: String!, $password: String!){
            signInUserByEmail(email: $email, password: $password) {
              token
            }
          }`, {
            email: this.form.email,
            password: this.form.password
          }).then((rst) => {
            this.$message({
              type: 'success',
              message: this.$t("flashes.success")
            })
            var token = rst.signInUserByEmail.token
            this.$store.commit('signIn', token)
            this.$router.push({
              name: 'users.logs'
            })
          }).catch(failed)
        } else {
          return false;
        }
      });
    },
    resetForm(formName) {
      this.$refs[formName].resetFields();
    }
  }
}
</script>

// dashboard/src/pages/users/SignIn.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import {connect} from 'react-redux'
import {push} from 'react-router-redux'
import {Form, Input, message} from 'antd'

import {Submit, formItemLayout} from '../../components/form'
import {client, USERS_SIGN_IN, failed} from '../../request'
import {TOKEN} from '../../Authorized'
import Layout from './Layout'
import {signIn} from '../../actions'

const FormItem = Form.Item

class Widget extends Component {
  handleSubmit = (e) => {
    const {push, signIn} = this.props
    const {formatMessage} = this.props.intl
    e.preventDefault()
    this.props.form.validateFields((err, values) => {
      if (!err) {
        client.request(USERS_SIGN_IN, values).then((rst) => {
          var token = rst.signInUserByEmail.token
          message.info(formatMessage({id: "flashes.success"}))
          localStorage.setItem(TOKEN, token)
          signIn(token)
          push('/users/logs')
        }).catch(failed)
      }
    })
  }
  render() {
    const {formatMessage} = this.props.intl
    const {getFieldDecorator} = this.props.form
    return (<Layout title="nut.users.sign-in.title">
      <Form onSubmit={this.handleSubmit}>
        <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.email" />} hasFeedback={true}>
          {
            getFieldDecorator('email', {
              rules: [
                {
                  type: 'email',
                  message: formatMessage({id: "validations.email"})
                }, {
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }
              ]
            })(<Input/>)
          }
        </FormItem>
        <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.password" />} hasFeedback={true}>
          {
            getFieldDecorator('password', {
              rules: [
                {
                  required: true,
                  max: 30,
                  min: 6,
                  message: formatMessage({id: "validations.password"})
                }
              ]
            })(<Input type="password"/>)
          }
        </FormItem>
        <Submit/>
      </Form>
    </Layout>)
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired,
  push: PropTypes.func.isRequired,
  signIn: PropTypes.func.isRequired
}

export default connect(state => ({}), {push, signIn})(Form.create()(injectIntl(Widget)))
