// desktop/src/plugins/nut/Install.vue
<template>
<application-layout>
  <document-title :title="title" />
  <el-card :header="title">
    <el-form :rules="rules" ref="form" :model="form" label-width="80px">
      <el-form-item :label="$t('attributes.username')" prop="name">
        <el-input v-model="form.name" clearable required/>
      </el-form-item>
      <el-form-item :label="$t('attributes.email')" prop="email">
        <el-input v-model="form.email" clearable required/>
      </el-form-item>
      <el-form-item :label="$t('attributes.password')" prop="password">
        <el-input type="password" v-model="form.password" clearable auto-complete="off" />
      </el-form-item>
      <el-form-item :label="$t('attributes.password-confirmation')" prop="passwordConfirmation">
        <el-input type="password" v-model="form.passwordConfirmation" clearable auto-complete="off" />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="submitForm('form')">{{$t('buttons.submit')}}</el-button>
        <el-button @click="resetForm('form')">{{$t('buttons.reset')}}</el-button>
      </el-form-item>
    </el-form>
    <shared-links />
  </el-card>
</application-layout>
</template>

<script>
import SharedLinks from './users/SharedLinks'
import {
  client,
  failed
} from '@/request'

export default {
  name: 'Install',
  components: {
    'shared-links': SharedLinks
  },
  data() {
    var validatePasswords = (rule, value, callback) => {
      if (value === '' || value !== this.form.password) {
        callback(new Error(this.$t('validations.password-confirmation')));
      } else {
        callback();
      }
    };
    return {
      title: this.$t('nut.install.title'),
      form: {
        email: '',
        name: '',
        password: '',
        passwordConfirmation: ''
      },
      rules: {
        name: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        email: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }, {
          type: 'email',
          message: this.$t('validations.email'),
          trigger: ['blur', 'change']
        }],
        password: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }, {
          min: 6,
          max: 32,
          message: this.$t('validations.password'),
          trigger: ['blur', 'change']
        }],
        passwordConfirmation: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }, {
          validator: validatePasswords,
          trigger: ['blur', 'change']
        }]
      }
    }
  },
  methods: {
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          client().request(`mutation form($name: String!, $email: String!, $password: String!){
            install(name: $name, email: $email, password: $password) {
              createdAt
            }
          }`, {
            name: this.form.name,
            email: this.form.email,
            password: this.form.password
          }).then((rst) => {
            this.$message({
              type: 'success',
              message: this.$t("flashes.success")
            })
            this.$router.push({
              name: 'users.sign-in'
            })
          }).catch(failed)
        } else {
          return false;
        }
      });
    },
    resetForm(formName) {
      this.$refs[formName].resetFields();
    }
  }
}
</script>

// dashboard/src/routes/Install.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import {connect} from 'react-redux'
import {push} from 'react-router-redux'
import {Form, Input, message, notification} from 'antd'

import Application from '../layouts/Application'
import {Submit, formItemLayout} from '../components/form'
import {client, INSTALL} from '../request'

const FormItem = Form.Item

class Widget extends Component {
  handleSubmit = (e) => {
    const {push} = this.props
    const {formatMessage} = this.props.intl
    e.preventDefault()
    this.props.form.validateFields((err, values) => {
      if (!err) {
        client.request(INSTALL, values).then((rst) => {
          message.info(formatMessage({id: "flashes.success"}))
          push('/users/sign-in')
        }).catch((err) => notification.error({
          message: formatMessage({id: "flashes.failed"}),
          description: JSON.stringify(err.response),
          duration: 30
        }))
      }
    })
  }
  checkPassword = (rule, value, callback) => {
    const {formatMessage} = this.props.intl
    const {getFieldValue} = this.props.form
    if (value && value !== getFieldValue('password')) {
      callback(formatMessage({id: "validations.password-confirmation"}));
    } else {
      callback();
    }
  }
  render() {
    const {formatMessage} = this.props.intl
    const {getFieldDecorator} = this.props.form
    return (<Application title="nut.install.title" submit={this.handleSubmit}>
      <Form onSubmit={this.handleSubmit}>
        <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.username" />} hasFeedback={true}>
          {
            getFieldDecorator('name', {
              rules: [
                {
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }
              ]
            })(<Input/>)
          }
        </FormItem>
        <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.email" />} hasFeedback={true}>
          {
            getFieldDecorator('email', {
              rules: [
                {
                  type: 'email',
                  message: formatMessage({id: "validations.email"})
                }, {
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }
              ]
            })(<Input/>)
          }
        </FormItem>
        <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.password" />} hasFeedback={true}>
          {
            getFieldDecorator('password', {
              rules: [
                {
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }
              ]
            })(<Input type="password"/>)
          }
        </FormItem>
        <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.password-confirmation" />} hasFeedback={true}>
          {
            getFieldDecorator('passwordConfirmation', {
              rules: [
                {
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }, {
                  validator: this.checkPassword
                }
              ]
            })(<Input type="password"/>)
          }
        </FormItem>
        <Submit/>
      </Form>
    </Application>);
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired,
  push: PropTypes.func.isRequired
}

export default connect(state => ({}), {push})(Form.create()(injectIntl(Widget)))
