// desktop/src/plugins/nut/admin/cards/Form.vue
<template>
<dashboard-layout :title="title" :role="null" :init="init">
  <col-form>
    <el-card :header="title">
      <el-form :rules="rules" ref="form" :model="form" label-width="80px">
        <el-form-item :label="$t('attributes.title')" prop="title">
          <el-input v-model="form.title" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.body')" prop="body">
          <quill-editor v-model="form.body" />
        </el-form-item>
        <el-form-item :label="$t('nut.attributes.card.action')" prop="action">
          <el-input v-model="form.action" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.url')" prop="href">
          <el-input v-model="form.href" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.logo')" prop="logo">
          <el-input v-model="form.logo" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.loc')">
          <el-select v-model="form.loc">
            <el-option v-for="it in ['top', 'middle', 'bottom']" :key="it" :label="it" :value="it" />
          </el-select>
        </el-form-item>
        <el-form-item :label="$t('attributes.position')">
          <el-select v-model="form.position">
            <el-option v-for="it in sort_orders" :key="it" :label="it" :value="it" />
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t('buttons.submit')}}</el-button>
          <el-button @click="go_back">{{$t('buttons.return')}}</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </col-form>
</dashboard-layout>
</template>

<script>
import {
  client,
  failed
} from '@/request'
import lodash from 'lodash'

export default {
  name: 'AdminCardsForm',
  data() {
    return {
      title: this.$t("nut.admin.cards.index.title"),
      form: {
        id: null,
        title: '',
        body: '',
        mediaType: 'html',
        action: '',
        href: '',
        logo: '',
        loc: 'top',
        position: 0,
      },
      rules: {
        title: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        body: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        action: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        href: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        logo: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }]
      }
    }
  },
  computed: {
    sort_orders() {
      return lodash.range(-9, 10)
    }
  },
  methods: {
    go_back() {
      this.$router.push({
        name: 'admin.cards.index'
      })
    },
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          var id = this.$route.params.id
          client().request(id ?
            `mutation form($id: String!, $title: String!, $body: String!, $mediaType: String!, $action: String!, $href: String!, $logo: String!, $loc: String!, $position: Int!){
            updateCard(id: $id, title: $title, body: $body, mediaType: $mediaType, action: $action, href: $href, logo: $logo, loc: $loc, position: $position) {
              createdAt
            }
          }` :
            `mutation form($title: String!, $body: String!, $mediaType: String!, $action: String!, $href: String!, $logo: String!, $loc: String!, $position: Int!){
            createCard(title: $title, body: $body, mediaType: $mediaType, action: $action, href: $href, logo: $logo, loc: $loc, position: $position) {
              createdAt
            }
          }`,
            this.form).then(() => {
            this.$message({
              type: 'success',
              message: this.$t("flashes.success")
            })
            this.go_back()
          }).catch(failed)
        } else {
          return false;
        }
      });
    },
    init() {
      var id = this.$route.params.id
      if (id) {
        client().request(`query info($id: String!){
        showCard(id: $id) {
          id, title, body, mediaType, action, href, logo, loc, position
        }
      }`, {
          id
        }).then((rst) => {
          this.form = rst.showCard
        }).catch(failed)
      }
    }
  }
}
</script>

// dashboard/src/plugins/nut/admin/cards/Form.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import {
  Form,
  Row,
  Col,
  Input,
  Select,
  message
} from 'antd'
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import {connect} from 'react-redux'
import {push} from 'react-router-redux'

import Layout from '../../../../layouts/dashboard'
import {post, get} from '../../../../ajax'
import {ADMIN} from '../../../../auth'
import {Submit, Quill, orders, formItemLayout} from '../../../../components/form'

const FormItem = Form.Item
const Option = Select.Option

class Widget extends Component {
  state = {
    summary: ''
  }
  componentDidMount() {
    const {setFieldsValue} = this.props.form
    const {id} = this.props.match.params
    if (id) {
      get(`/admin/cards/${id}`).then((rst) => {
        setFieldsValue({
          title: rst.title,
          action: rst.action,
          logo: rst.logo,
          href: rst.href,
          sort: rst.sort.toString(),
          loc: rst.loc
        })
        this.setState({summary: rst.summary})
      }).catch(message.error)
    } else {
      setFieldsValue({sort: '0', loc: 'album-main'})
    }
  }
  handleChange = (value) => {
    this.setState({summary: value})
  }
  handleSubmit = (e) => {
    const {formatMessage} = this.props.intl
    const {push} = this.props
    const {id} = this.props.match.params
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        post(
          id
          ? `/admin/cards/${id}`
          : '/admin/cards',
        Object.assign({}, values, {
          sort: parseInt(values.sort, 10),
          type: 'html',
          summary: this.state.summary
        })).then(() => {
          message.success(formatMessage({id: "flash.success"}))
          push('/admin/cards')
        }).catch(message.error);
      }
    });
  }
  render() {
    const {formatMessage} = this.props.intl
    const {getFieldDecorator} = this.props.form
    const {id} = this.props.match.params
    const title = id
      ? {
        id: "buttons.edit",
        values: {
          id: id
        }
      }
      : {
        id: "buttons.new"
      }
    return (<Layout breads={[
        {
          href: '/admin/cards',
          label: {
            id: 'nut.admin.cards.index.title'
          }
        },
        id
          ? {
            href: `/admin/cards/edit/${id}`,
            label: title
          }
          : {
            href: "/admin/cards/new",
            label: title
          }
      ]} title={title} roles={[ADMIN]}>
      <Row>
        <Col md={{
            span: 18
          }}>
          <Form onSubmit={this.handleSubmit}>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.loc" />}>
              {
                getFieldDecorator('loc')(<Select>
                  {['album-header', 'album-main', 'carousel-top', 'carousel-middle', 'carousel-bottom'].map((p) => (<Option key={p} value={p}>{p}</Option>))}
                </Select>)
              }
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.sort-order" />}>
              {
                getFieldDecorator('sort')(<Select>
                  {orders(10).map((p) => (<Option key={p} value={p}>{p}</Option>))}
                </Select>)
              }
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.title" />} hasFeedback={true}>
              {
                getFieldDecorator('title', {
                  rules: [
                    {
                      required: true,
                      message: formatMessage({id: "validator.required"})
                    }
                  ]
                })(<Input/>)
              }
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.logo" />} hasFeedback={true}>
              {
                getFieldDecorator('logo', {
                  rules: [
                    {
                      required: true,
                      message: formatMessage({id: "validator.required"})
                    }
                  ]
                })(<Input/>)
              }
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.summary" />}>
              <Quill value={this.state.summary} onChange={this.handleChange}/>
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.action" />} hasFeedback={true}>
              {
                getFieldDecorator('action', {
                  rules: [
                    {
                      required: true,
                      message: formatMessage({id: "validator.required"})
                    }
                  ]
                })(<Input/>)
              }
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.href" />} hasFeedback={true}>
              {
                getFieldDecorator('href', {
                  rules: [
                    {
                      required: true,
                      message: formatMessage({id: "validator.required"})
                    }
                  ]
                })(<Input/>)
              }
            </FormItem>
            <Submit/>
          </Form>
        </Col>
      </Row>
    </Layout>);
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired,
  push: PropTypes.func.isRequired
}

const WidgetF = Form.create()(injectIntl(Widget))

export default connect(state => ({}), {
  push
},)(WidgetF)
