// dashboard/src/pages/admin/members/index.jsx
import React, {
  Component
} from 'react'
import {
  FormattedMessage,
  intlShape,
  injectIntl
} from 'react-intl'
import router from 'umi/router'
import {
  List,
  Button,
  Popconfirm,
  message
} from 'antd';

import Layout from "../../../components/layouts/Table"
import Authorized from '../../../components/Authorized'
import {
  failed,
  client
} from '../../../utils/request'
import {
  is_administrator
} from '../../../utils/authorized'

class Widget extends Component {
  constructor(props) {
      super(props)
      this.state = {
          items: [],
          columns: [{
                title: (<FormattedMessage id="attributes.username"/>),
                render: (text, record) => `${record.nickName}[${record.realName}]`,
                width: 320,
                key: 'user'
              }, {
                title: (<FormattedMessage id="attributes.gender"/>),
                render: (text, record) => <FormattedMessage id={`attributes.gender-${record.gender}`}/>,
                width: 80,
                key: 'gender'
              }, {
                title: (<FormattedMessage id="attributes.contact"/>),
                render: (text, record) => (<List
                  size="small"
                  bordered
                  dataSource={['phone', 'email', 'address', 'line', 'wechat', 'skype', 'weibo', 'facebook'].map((it)=>(<span key={it}><FormattedMessage id={`nut.attributes.member.${it}`}/>: {record[it]}</span>))}
                  renderItem={it => (<List.Item>{it}</List.Item>)}/>),
        key: 'contact'
      }, {
        title: (<span><FormattedMessage id="buttons.operator"/>&nbsp;<Button onClick={()=>router.push(`/admin/members/new`)} size="small" shape="circle" type="primary" icon="file-add"/></span>),
        width: 120,
        render: (text, record) => (<span>
          <Button size="small" onClick={()=>router.push(`/admin/members/${record.id}/edit`)} shape="circle" type="dashed" icon="edit"/>
          <Popconfirm title={<FormattedMessage id="flashes.confirm-to-remove" values={{name:record.nickName}} />} onConfirm={(e) => this.handleRemove(record.id)}>
            <Button size="small" shape="circle" type="danger" icon="delete"/>
          </Popconfirm>
        </span>),
        key: 'operator'
      }]
    }
  }
  handleRemove = (id) => {
    const {
      formatMessage
    } = this.props.intl
    client().request(`mutation form($id: String!){
          removeMember(id: $id) {
            createdAt
          }
        }`, {
      id
    }).then(() => {
      message.info(formatMessage({
        id: "flashes.success"
      }))
      var items = this.state.items.filter((it) => it.id !== id)
      this.setState({items})
    }).catch(failed)
  }
  componentDidMount() {
    client().request(`query list{
        listMember{
          id, nickName, realName, gender, birthday, phone, email, address, line, wechat, skype, weibo, facebook
        }
      }`).then((rst) => {
      this.setState({
        items: rst.listMember
      })
    }).catch(failed)
  }
  render() {
    const {
      items,
      columns
    } = this.state
    return (<Authorized check={is_administrator}>
      <Layout rowKey="id" title={{
        id: "nut.admin.members.index.title"
      }} items={items} columns={columns}/>
    </Authorized>)
  }
}


Widget.propTypes = {
  intl: intlShape.isRequired
}

export default injectIntl(Widget)

// desktop/src/plugins/nut/admin/members/Index.vue
<template>
<dashboard-layout :title="title" :role="role" :init="init">
  <div style="float: right;">
    <el-button size="mini" type="primary" @click="()=>this.$router.push({name:'admin.members.new'})" class="el-icon-plus" />
  </div>
  <el-pagination @current-change="setPage" :page-size="size" layout="total, prev, pager, next" :total="items.length" />
  <el-table :data="table" border>
    <el-table-column :label="$t('attributes.username')" width="320">
      <template slot-scope="scope">
        {{scope.row.nickName}}[{{scope.row.realName}}]({{$t(`attributes.gender-${scope.row.gender}`)}})
      </template>
    </el-table-column>
    <el-table-column :label="$t('attributes.contact')">
      <template slot-scope="scope">
        <el-card shadow="never">
          <div v-if="scope.row[it]" v-for="it in ['phone', 'email', 'address', 'line', 'wechat', 'skype', 'weibo', 'facebook']" :key="it">
            {{$t(`nut.attributes.member.${it}`)}}: {{scope.row[it]}}
          </div>
        </el-card>
      </template>
    </el-table-column>
    <el-table-column fixed="right" :label="$t('buttons.operator')" width="120">
      <template slot-scope="scope">
        <el-button-group>
          <el-button size="mini" type="warning" @click="handleEdit(scope.row.id)" class="el-icon-edit"/>
          <el-button size="mini" type="danger" @click="handleDelete(scope.row.id, scope.row.nickName)" class="el-icon-delete"/>
        </el-button-group>
      </template>
    </el-table-column>
  </el-table>
</dashboard-layout>
</template>

<script>
import {
  client,
  failed
} from '@/request'
import lodash from 'lodash'
import {
  ADMIN
} from '@/authorized'

export default {
  name: 'AdminMembersIndex',
  data() {
    return {
      role: {
        name: ADMIN,
        type: null,
        id: null
      },
      title: this.$t("nut.admin.members.index.title"),
      size: 12,
      page: 1,
      items: []
    }
  },
  computed: {
    table() {
      var offset = (this.page - 1) * this.size;
      return lodash(this.items).slice(offset).take(this.size).value()
    }
  },
  methods: {
    handleEdit(id) {
      this.$router.push({
        name: 'admin.members.edit',
        params: {
          id
        }
      })
    },
    handleDelete(id, name) {
      this.$confirm(this.$t('are-you-sure.delete', {
        id: name
      }), this.$t('flashes.info'), {
        confirmButtonText: this.$t('buttons.ok'),
        cancelButtonText: this.$t('buttons.cancel'),
        type: 'warning',
        center: true
      }).then(() => {
        client().request(`mutation form($id: String!){
          removeMember(id: $id) {
            createdAt
          }
        }`, {
          id
        }).then(() => {
          this.items = this.items.filter((it) => {
            return it.id !== id
          })
        }).catch(failed)
      }).catch(() => {})

    },
    init() {
      client().request(`query list{
        listMember{
          id, nickName, realName, gender, birthday, phone, email, address, line, wechat, skype, weibo, facebook
        }
      }`, {}).then((rst) => {
        this.items = rst.listMember
      }).catch(failed)
    },
    setPage(p) {
      this.page = p
    }
  }
}
</script>
