// by-vue/src/plugins/nut/users/Confirm.vue
<template>
<application-layout :title="$t('users.confirm.title')" :on-submit="onSubmit">
  <v-text-field prepend-icon="person" :label="$t('attributes.email')" type="text" />
</application-layout>
</template>


<script>
export default {
  name: 'UsersConfirm',
  methods: {
    onSubmit: function(event) {
      event.preventDefault()
      console.log('confirm')
    }
  }
}
</script>

// dashboard/src/routes/users/Confirm.jsx
import React, {
  Component
} from 'react'

import Application from '../../layouts/Application'

class Widget extends Component {
  handleSubmit = (e) => {
    e.preventDefault();
    console.log('aaa')
  }
  render() {
    return (<Application title="nut.users.confirm.title" submit={this.handleSubmit}>
      users.confirm
    </Application>);
  }
}

export default Widget;
