// by-vue/src/plugins/nut/users/SignIn.vue
<template>
<application-layout :title="$t('users.sign-in.title')" :on-submit="onSubmit">
  <v-text-field prepend-icon="person" :label="$t('attributes.email')" type="text" />
  <v-text-field prepend-icon="lock" :label="$t('attributes.password')" type="password" />
</application-layout>
</template>


<script>
export default {
  name: 'UsersSignIn',
  methods: {
    onSubmit: function(event) {
      event.preventDefault()
      console.log('sign in')
    }
  }
}
</script>

// dashboard/src/routes/users/SignIn.jsx
import React, {
  Component
} from 'react'

import Application from '../../layouts/Application'

class Widget extends Component {
  handleSubmit = (e) => {
    e.preventDefault();
    console.log('aaa')
  }
  render() {
    return (<Application title="nut.users.sign-in.title" submit={this.handleSubmit}>
      users.sign-in
    </Application>);
  }
}

export default Widget;
