// by-vue/src/plugins/nut/users/SignUp.vue
<template>
<application-layout :title="$t('users.sign-up.title')" :on-submit="onSubmit">
  <v-text-field prepend-icon="person" label="Login" type="text" />
  <v-text-field prepend-icon="lock" label="Password" type="password" />
  <v-text-field prepend-icon="lock" label="Password" type="password" />
</application-layout>
</template>


<script>
export default {
  name: 'UsersSignUp',
  methods: {
    onSubmit: function(event) {
      event.preventDefault()
      console.log('sign up')
    }
  }
}
</script>

// dashboard/src/routes/users/SignUp.jsx
import React, {
  Component
} from 'react'

import Application from '../../layouts/Application'

class Widget extends Component {
  handleSubmit = (e) => {
    e.preventDefault();
    console.log('aaa')
  }
  render() {
    return (<Application title="nut.users.sign-up.title" submit={this.handleSubmit}>
      users.sign-up
    </Application>);
  }
}

export default Widget;
