// dashboard/src/pages/admin/users/index.jsx
import React, {
  Component
} from 'react'
import {
  FormattedMessage,
  intlShape,
  injectIntl
} from 'react-intl'
import router from 'umi/router'
import {
  Button,
  Popconfirm,
  message
} from 'antd';

import Layout from "../../../components/layouts/Table"
import Authorized from '../../../components/Authorized'
import {
  failed,
  client
} from '../../../utils/request'
import {
  show as moment
} from '../../../utils/moment'
import {
  is_administrator
} from '../../../utils/authorized'

const show_sign_in = (at, ip) => `${at ? moment(at) : ''}[${ip ? ip : ''}]`

class Widget extends Component {
  constructor(props) {
    super(props)
    this.state = {
      items: [],
      columns: [{
        title: (<FormattedMessage id="attributes.user"/>),
        render: (text, record) => `${record.name}\u003C${record.email}\u003E[${record.signInCount}]`,
        width: 320,
        key: 'user'
      }, {
        title: (<FormattedMessage id="nut.attributes.user.last-sign-in"/>),
        render: (text, record) => show_sign_in(record.lastSignInAt, record.lastSignInIp),
        key: 'last-sign-in'
      }, {
        title: (<FormattedMessage id="nut.attributes.user.current-sign-in"/>),
        render: (text, record) => show_sign_in(record.currentSignInAt, record.currentSignInIp),
        key: 'current-sign-in'
      }, {
        title: (<FormattedMessage id="buttons.operator"/>),
        width: 90,
        render: (text, record) => (<span>
          <Button size="small" onClick={()=>router.push(`/admin/users/${record.id}/policies`)} shape="circle" type="dashed" icon="edit"/>
          <Popconfirm title={<FormattedMessage id="nut.admin.users.index.lock.confirm" values={{name:record.name}} />} onConfirm={(e) => this.handleLock(record.id)}>
            <Button size="small" shape="circle" type="danger" icon="lock"/>
          </Popconfirm>
        </span>),
        key: 'operator'
      }]
    }
  }
  handleLock = (id) => {
    const {
      formatMessage
    } = this.props.intl
    client().request(`mutation form($id: String!){
        lockUser(id: $id) {
          createdAt
        }
      }`, {
      id
    }).then(() => {
      message.info(formatMessage({
        id: "flashes.success"
      }))
    }).catch(failed)
  }
  componentDidMount() {
    client().request(`query list{
        listUser{
          id, name, email, lastSignInAt, lastSignInIp, currentSignInAt, currentSignInIp, signInCount
        }
      }`).then((rst) => {
      this.setState({
        items: rst.listUser
      })
    }).catch(failed)
  }
  render() {
    const {
      items,
      columns
    } = this.state
    return (<Authorized check={is_administrator}>
      <Layout rowKey="id" title={{
        id: "nut.admin.users.index.title"
      }} items={items} columns={columns}/>
    </Authorized>)
  }
}


Widget.propTypes = {
  intl: intlShape.isRequired
}

export default injectIntl(Widget)

// desktop/src/plugins/nut/admin/users/Index.vue
<template>
<dashboard-layout :title="title" :role="role" :init="init">
  <el-pagination @current-change="setPage" :page-size="size" layout="total, prev, pager, next" :total="items.length" />
  <el-table :data="table" border>
    <el-table-column :label="$t('nut.attributes.user.info')">
      <template slot-scope="scope">
        {{scope.row.name}}&lt;{{scope.row.email}}&gt;[{{scope.row.signInCount}}]
      </template>
    </el-table-column>
    <el-table-column :label="$t('nut.attributes.user.last-sign-in')">
      <template slot-scope="scope">
        {{scope.row.lastSignInAt}}[{{scope.row.lastSignInIp}}]
      </template>
    </el-table-column>
    <el-table-column :label="$t('nut.attributes.user.current-sign-in')">
      <template slot-scope="scope">
        {{scope.row.currentSignInAt}}[{{scope.row.currentSignInIp}}]
      </template>
    </el-table-column>
    <el-table-column fixed="right" :label="$t('buttons.operator')" width="120">
      <template slot-scope="scope">
        <el-button-group>
          <el-button size="mini" type="warning" @click="handlePolicy(scope.row.id)" class="el-icon-menu"/>
          <el-button size="mini" type="danger" @click="handleLock(scope.row.id, scope.row.name)" class="el-icon-bell"/>
        </el-button-group>
      </template>
    </el-table-column>
  </el-table>
</dashboard-layout>
</template>

<script>
import {
  client,
  failed
} from '@/request'
import lodash from 'lodash'
import {
  ADMIN
} from '@/authorized'

export default {
  name: 'AdminUsersIndex',
  data() {
    return {
      role: ADMIN,
      title: this.$t("nut.admin.users.index.title"),
      size: 12,
      page: 1,
      items: []
    }
  },
  computed: {
    table() {
      var offset = (this.page - 1) * this.size;
      return lodash(this.items).slice(offset).take(this.size).value()
    }
  },
  methods: {
    handlePolicy(id) {
      this.$router.push({
        name: 'admin.users.policy',
        params: {
          id
        }
      })
    },
    handleLock(id, name) {
      this.$confirm(this.$t('nut.admin.users.index.lock', {
        name
      }), this.$t('flashes.info'), {
        confirmButtonText: this.$t('buttons.ok'),
        cancelButtonText: this.$t('buttons.cancel'),
        type: 'warning',
        center: true
      }).then(() => {
        client().request(`mutation form($id: String!){
          lockUser(id: $id) {
            createdAt
          }
        }`, {
          id
        }).then(() => {
          this.$message({
            type: 'success',
            message: this.$t("flashes.success")
          })
        }).catch(failed)
      }).catch(() => {})

    },
    init() {
      client().request(`query list{
        listUser{
          id, name, email, lastSignInAt, lastSignInIp, currentSignInAt, currentSignInIp, signInCount
        }
      }`, {}).then((rst) => {
        this.items = rst.listUser
      }).catch(failed)
    },
    setPage(p) {
      this.page = p
    }
  }
}
</script>
