// old/src-old/ds/src/plugins/nut/admin/locales/Form.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import {Form, Row, Col, Input, message} from 'antd'
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import {connect} from 'react-redux'
import {push} from 'react-router-redux'

import Layout from '../../../../layouts/dashboard'
import {post, get} from '../../../../ajax'
import {ADMIN} from '../../../../auth'
import {Submit, formItemLayout} from '../../../../components/form'

const FormItem = Form.Item

class Widget extends Component {
  componentDidMount() {
    const {setFieldsValue} = this.props.form
    const {id} = this.props.match.params
    if (id) {
      get(`/admin/locales/${id}`).then((rst) => setFieldsValue({code: rst.code, message: rst.message})).catch(message.error)
    }
  }
  handleSubmit = (e) => {
    const {formatMessage} = this.props.intl
    const {push} = this.props
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        post('/admin/locales', values).then(() => {
          message.success(formatMessage({id: "flash.success"}))
          push('/admin/locales')
        }).catch(message.error);
      }
    });
  }
  render() {
    const {formatMessage} = this.props.intl
    const {getFieldDecorator} = this.props.form
    const {code} = this.props.match.params
    const title = code
      ? {
        id: "buttons.edit",
        values: {
          id: code
        }
      }
      : {
        id: "buttons.new"
      }
    return (<Layout breads={[
        {
          href: '/admin/locales',
          label: {
            id: 'nut.admin.locales.index.title'
          }
        },
        code
          ? {
            href: `/admin/locales/edit/${code}`,
            label: title
          }
          : {
            href: "/admin/locales/new",
            label: title
          }
      ]} title={title} roles={[ADMIN]}>
      <Row>
        <Col md={{
            span: 12,
            offset: 2
          }}>
          <Form onSubmit={this.handleSubmit}>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "nut.attributes.locale.code" />} hasFeedback={true}>
              {
                getFieldDecorator('code', {
                  rules: [
                    {
                      required: true,
                      message: formatMessage({id: "validator.required"})
                    }
                  ]
                })(<Input/>)
              }
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "nut.attributes.locale.message" />} hasFeedback={true}>
              {
                getFieldDecorator('message', {
                  rules: [
                    {
                      required: true,
                      message: formatMessage({id: "validator.required"})
                    }
                  ]
                })(<Input.TextArea rows={6}/>)
              }
            </FormItem>
            <Submit/>
          </Form>
        </Col>
      </Row>
    </Layout>);
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired,
  push: PropTypes.func.isRequired
}

const WidgetF = Form.create()(injectIntl(Widget))

export default connect(state => ({}), {
  push
},)(WidgetF)

// desktop/src/plugins/nut/admin/locales/Form.vue
<template>
<dashboard-layout :title="title" :role="null" :init="init">
  <col-form>
    <el-card :header="title">
      <el-form :rules="rules" ref="form" :model="form" label-width="80px">
        <el-form-item :label="$t('nut.attributes.locale.code')" prop="code">
          <el-input v-model="form.code" :disabled="this.$route.params.code ? true : false" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.content')" prop="message">
          <el-input type="textarea" v-model="form.message" clearable required/>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t('buttons.submit')}}</el-button>
          <el-button @click="go_back">{{$t('buttons.return')}}</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </col-form>
</dashboard-layout>
</template>

<script>
import {
  client,
  failed
} from '@/request'

export default {
  name: 'UsersProfile',
  data() {
    return {
      title: this.$t("nut.admin.locales.index.title"),
      form: {
        code: '',
        message: '',
      },
      rules: {
        code: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        message: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }]
      }
    }
  },
  methods: {
    go_back() {
      this.$router.push({
        name: 'admin.locales.index'
      })
    },
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          client().request(`mutation form($code: String!, $message: String!){
            updateLocale(code: $code, message: $message) {
              createdAt
            }
          }`, {
            code: this.form.code,
            message: this.form.message
          }).then(() => {
            this.$message({
              type: 'success',
              message: this.$t("flashes.success")
            })
            this.go_back()
          }).catch(failed)
        } else {
          return false;
        }
      });
    },
    init() {
      var code = this.$route.params.code
      if (code) {
        this.form.code = code
        client().request(`query info($code: String!){
        getLocale(code: $code) {
          message
        }
      }`, {
          code
        }).then((rst) => {
          var ifo = rst.getLocale
          this.form.message = ifo.message
        }).catch(failed)
      }
    }
  }
}
</script>
