// desktop/src/plugins/nut/leave-words/New.vue
<template>
<application-layout :title="title">
  <el-card :header="title">
    <el-form :rules="rules" ref="form" :model="form" label-width="80px">
      <el-form-item :label="$t('attributes.content')" prop="body">
        <el-input type='textarea' v-model="form.body" clearable />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="submitForm('form')">{{$t('buttons.submit')}}</el-button>
        <el-button @click="resetForm('form')">{{$t('buttons.reset')}}</el-button>
      </el-form-item>
    </el-form>
    <shared-links />
  </el-card>
</application-layout>
</template>

<script>
import SharedLinks from '../users/SharedLinks'
import {
  client,
  failed
} from '@/request'

export default {
  name: 'NewLeaveWord',
  components: {
    'shared-links': SharedLinks
  },
  data() {
    return {
      title: this.$t('nut.leave-words.new.title'),
      form: {
        body: ''
      },
      rules: {
        body: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }]
      }
    }
  },
  methods: {
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          client().request(`mutation form($mediaType: String!, $body: String!){
            createLeaveWord(mediaType: $mediaType, body: $body) {
              createdAt
            }
          }`, {
            body: this.form.body,
            mediaType: 'text'
          }).then(() => {
            this.$message({
              type: 'success',
              message: this.$t("flashes.success")
            })
            this.form.body = ' '
          }).catch(failed)
        } else {
          return false;
        }
      });
    },
    resetForm(formName) {
      this.$refs[formName].resetFields();
    }
  }
}
</script>

// dashboard/src/pages/leave-words/new.jsx
import React, {
  Component
} from 'react'
import {
  injectIntl,
  intlShape,
  FormattedMessage
} from 'react-intl'
import {
  Form,
  Input,
  message
} from 'antd'

import Layout from "../../components/layouts/UsersSharedLinks"
import {
  Submit,
  formItemLayout
} from '../../components/form'
import {
  client,
  failed
} from '../../utils/request'

const FormItem = Form.Item

class Widget extends Component {
  handleSubmit = (e) => {
    const {
      formatMessage
    } = this.props.intl
    e.preventDefault()
    this.props.form.validateFields((err, values) => {
      if (!err) {
        client().request(`mutation form($mediaType: String!, $body: String!){
            createLeaveWord(mediaType: $mediaType, body: $body) {
              createdAt
            }
          }`, {
          body: values.body,
          mediaType: 'text'
        }).then((rst) => {
          message.info(formatMessage({
            id: "flashes.success"
          }))
        }).catch(failed)
      }
    })
  }
  render() {
    const {
      formatMessage
    } = this.props.intl
    const {
      getFieldDecorator
    } = this.props.form
    return (<Layout title='nut.leave-words.new.title'>
      <Form onSubmit={this.handleSubmit}>
        <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.content" />} extra={<FormattedMessage id = "nut.leave-words.new.body-helper" />} hasFeedback={true}>
          {
            getFieldDecorator('body', {
              rules: [
              {
                  required: true,
                message: formatMessage({id: "validations.required"})
              }
              ]
            })(<Input.TextArea rows={8}/>)
          }
        </FormItem>
        <Submit/>
      </Form>
    </Layout>)
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired
}

export default Form.create()(injectIntl(Widget))
