// desktop/src/plugins/nut/admin/site/Smtp.vue
<template>
<dashboard-layout :title="title" :role="null" :init="init">
  <col-form>
    <el-card :header="title">
      <el-form :rules="rules" ref="form" :model="form" label-width="80px">
        <el-form-item :label="$t('attributes.host')" prop="host">
          <el-input v-model="form.host" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.port')">
          <el-select v-model="form.port">
            <el-option v-for="it in [25, 465, 587]" :key="it" :label="it" :value="it" />
          </el-select>
        </el-form-item>
        <el-form-item :label="$t('nut.attributes.smtp.user')" prop="user">
          <el-input v-model="form.user" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.password')" prop="password">
          <el-input type="password" v-model="form.password" clearable auto-complete="off" />
        </el-form-item>
        <el-form-item :label="$t('attributes.password-confirmation')" prop="passwordConfirmation">
          <el-input type="password" v-model="form.passwordConfirmation" clearable auto-complete="off" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t('buttons.submit')}}</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </col-form>
</dashboard-layout>
</template>

<script>
import {
  client,
  failed
} from '@/request'

export default {
  name: 'AdminSiteAuthor',
  data() {
    var validatePasswords = (rule, value, callback) => {
      if (value === '' || value !== this.form.password) {
        callback(new Error(this.$t('validations.password-confirmation')));
      } else {
        callback();
      }
    };

    return {
      title: this.$t("nut.admin.site.smtp.title"),
      form: {
        host: '',
        port: 25,
        user: '',
        password: '',
        passwordConfirmation: ''
      },
      rules: {
        host: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        user: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }, {
          type: 'email',
          message: this.$t('validations.email'),
          trigger: ['blur', 'change']
        }],
        password: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }, {
          min: 6,
          max: 32,
          message: this.$t('validations.password'),
          trigger: ['blur', 'change']
        }],
        passwordConfirmation: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }, {
          validator: validatePasswords,
          trigger: ['blur', 'change']
        }]
      }
    }
  },
  methods: {
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          client().request(
            `mutation form($host: String!, $port: Int!, $user: String!, $password: String!){
            updateSiteSmtp(host: $host, port: $port, user: $user, password: $password) {
              createdAt
            }
          }`,
            this.form).then(() => {
            this.$message({
              type: 'success',
              message: this.$t("flashes.success")
            })
          }).catch(failed)
        } else {
          return false;
        }
      });
    },
    init() {
      client().request(`query info{
        getSiteSmtp{
          host, port, user, password
        }
      }`, {}).then((rst) => {
        this.form = Object.assign({
          passwordConfirmation: ''
        }, rst.getSiteSmtp)
      }).catch(() => {})
    }
  }
}
</script>

// dashboard/src/plugins/nut/admin/site/Smtp.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import {
  Form,
  Row,
  Col,
  Input,
  Select,
  Button,
  Popconfirm,
  message
} from 'antd'
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import {connect} from 'react-redux'
import {push} from 'react-router-redux'

import Layout from '../../../../layouts/dashboard'
import {post, get, patch} from '../../../../ajax'
import {ADMIN} from '../../../../auth'
import {Submit, formItemLayout} from '../../../../components/form'

const FormItem = Form.Item
const Option = Select.Option

class Widget extends Component {
  componentDidMount() {
    const {setFieldsValue} = this.props.form
    get('/admin/site/smtp').then((rst) => setFieldsValue(Object.assign({}, rst, {port: rst.port.toString()}))).catch(message.error)
  }
  handleSubmit = (e) => {
    const {formatMessage} = this.props.intl
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        post('/admin/site/smtp', Object.assign({}, values, {
          port: parseInt(values.port, 10)
        })).then(() => {
          message.success(formatMessage({id: "flash.success"}))
        }).catch(message.error);
      }
    });
  }
  checkPassword = (rule, value, callback) => {
    const {formatMessage} = this.props.intl
    const {getFieldValue} = this.props.form
    if (value && value !== getFieldValue('password')) {
      callback(formatMessage({id: "validator.password-confirmation"}));
    } else {
      callback();
    }
  }
  handleTest = () => {
    const {formatMessage} = this.props.intl
    this.props.form.validateFields((err, values) => {
      if (!err) {
        patch('/admin/site/smtp', Object.assign({}, values, {
          port: parseInt(values.port, 10)
        })).then(() => {
          message.success(formatMessage({id: "flash.success"}))
        }).catch(message.error);
      }
    });
  }
  render() {
    const {formatMessage} = this.props.intl
    const {getFieldDecorator} = this.props.form
    const title = {
      id: "nut.admin.site.smtp.title"
    }
    return (<Layout breads={[{
          href: "/admin/site/smtp",
          label: title
        }
      ]} title={title} roles={[ADMIN]}>
      <Row>
        <Col md={{
            span: 12,
            offset: 2
          }}>
          <Form onSubmit={this.handleSubmit}>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.host" />} hasFeedback={true}>
              {
                getFieldDecorator('host', {
                  rules: [
                    {
                      required: true,
                      message: formatMessage({id: "validator.required"})
                    }
                  ]
                })(<Input/>)
              }
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.port" />}>
              {
                getFieldDecorator('port')(<Select>
                  {["25", "465", "587"].map((p) => (<Option key={p} value={p}>{p}</Option>))}
                </Select>)
              }
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.user" />} hasFeedback={true}>
              {
                getFieldDecorator('username', {
                  rules: [
                    {
                      type: 'email',
                      message: formatMessage({id: "validator.email"})
                    }, {
                      required: true,
                      message: formatMessage({id: "validator.required"})
                    }
                  ]
                })(<Input/>)
              }
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.password" />} hasFeedback={true}>
              {
                getFieldDecorator('password', {
                  rules: [
                    {
                      required: true,
                      message: formatMessage({id: "validator.required"})
                    }
                  ]
                })(<Input type="password"/>)
              }
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.password-confirmation" />} hasFeedback={true}>
              {
                getFieldDecorator('passwordConfirmation', {
                  rules: [
                    {
                      required: true,
                      message: formatMessage({id: "validator.required"})
                    }, {
                      validator: this.checkPassword
                    }
                  ]
                })(<Input type="password"/>)
              }
            </FormItem>
            <Submit>
              &nbsp; &nbsp;
              <Popconfirm title={<FormattedMessage id = "helpers.are-you-sure" />} onConfirm={this.handleTest}>
                <Button type="danger">
                  <FormattedMessage id="buttons.test"/>
                </Button>
              </Popconfirm>
            </Submit>
          </Form>
        </Col>
      </Row>
    </Layout>);
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired,
  push: PropTypes.func.isRequired,
  user: PropTypes.object.isRequired
}

const WidgetF = Form.create()(injectIntl(Widget))

export default connect(state => ({user: state.currentUser}), {
  push
},)(WidgetF)
