// dashboard/src/pages/admin/leave-words/index.jsx
import React, {
  Component
} from 'react'
import {
  FormattedMessage,
  intlShape,
  injectIntl
} from 'react-intl'
import {
  Button,
  Popconfirm,
  message
} from 'antd';

import Layout from "../../../components/layouts/Table"
import Authorized from '../../../components/Authorized'
import {
  failed,
  client
} from '../../../utils/request'
import {
  is_administrator
} from '../../../utils/authorized'
import {
  show as moment
} from '../../../utils/moment'

class Widget extends Component {
  constructor(props) {
    super(props)
    this.state = {
      items: [],
      columns: [{
        title: (<FormattedMessage id="attributes.updated-at"/>),
        render: (text, record) => moment(record.createdAt),
        width: 280,
        key: 'updatedAt'
      }, {
        title: (<FormattedMessage id="attributes.content"/>),
        render: (text, record) => <pre>{record.body}</pre>,
        key: 'body'
      }, {
        title: (<FormattedMessage id="buttons.operator"/>),
        width: 120,
        render: (text, record) => (<span>
          <Popconfirm title={<FormattedMessage id="flashes.confirm-to-remove" values={{name:record.id}} />} onConfirm={(e) => this.handleRemove(record.id)}>
            <Button size="small" shape="circle" type="danger" icon="delete"/>
          </Popconfirm>
        </span>),
        key: 'operator'
      }]
    }
  }
  handleRemove = (id) => {
    const {
      formatMessage
    } = this.props.intl
    client().request(`mutation form($id: String!){
          removeLeaveWord(id: $id) {
            createdAt
          }
        }`, {
      id
    }).then(() => {
      message.info(formatMessage({
        id: "flashes.success"
      }))
      var items = this.state.items.filter((it) => it.id !== id)
      this.setState({
        items
      })
    }).catch(failed)
  }
  componentDidMount() {
    client().request(`query list{
        listLeaveWord{
          id, body, createdAt
        }
      }`, {}).then((rst) => {
      this.setState({
        items: rst.listLeaveWord
      })
    }).catch(failed)
  }
  render() {
    const {
      items,
      columns
    } = this.state
    return (<Authorized check={is_administrator}>
      <Layout rowKey="id" title={{
        id: "nut.admin.leave-words.index.title"
      }} items={items} columns={columns}/>
    </Authorized>)
  }
}


Widget.propTypes = {
  intl: intlShape.isRequired
}

export default injectIntl(Widget)

// desktop/src/plugins/nut/admin/leave-words/Index.vue
<template>
<dashboard-layout :title="title" :role="role" :init="init">
  <el-pagination @current-change="setPage" :page-size="size" layout="total, prev, pager, next" :total="items.length" />
  <el-table :data="table" border>
    <el-table-column prop="id" :label="$t('attributes.id')" width="60" />
    <el-table-column prop="createdAt" :label="$t('attributes.createdAt')" width="240">
      <template slot-scope="scope">
        <timestamp :value="scope.row.createdAt"/>
      </template>
    </el-table-column>
    <el-table-column :label="$t('attributes.content')">
      <template slot-scope="scope">
        <pre>{{scope.row.body}}</pre>
      </template>
    </el-table-column>
    <el-table-column fixed="right" :label="$t('buttons.operator')" width="120">
      <template slot-scope="scope">
        <el-button size="mini" type="danger" @click="handleDelete(scope.row.id)" class="el-icon-delete"/>
      </template>
    </el-table-column>
  </el-table>
</dashboard-layout>
</template>

<script>
import {
  client,
  failed
} from '@/request'
import lodash from 'lodash'
import {
  ADMIN
} from '@/authorized'

export default {
  name: 'AdminLeaveWordsIndex',
  data() {
    return {
      role: ADMIN,
      title: this.$t("nut.admin.leave-words.index.title"),
      size: 12,
      page: 1,
      items: []
    }
  },
  computed: {
    table() {
      var offset = (this.page - 1) * this.size;
      return lodash(this.items).slice(offset).take(this.size).value()
    }
  },
  methods: {
    handleDelete(id) {
      this.$confirm(this.$t('are-you-sure.delete', {
        id
      }), this.$t('flashes.info'), {
        confirmButtonText: this.$t('buttons.ok'),
        cancelButtonText: this.$t('buttons.cancel'),
        type: 'warning',
        center: true
      }).then(() => {
        client().request(`mutation form($id: String!){
          removeLeaveWord(id: $id) {
            createdAt
          }
        }`, {
          id
        }).then(() => {
          this.items = this.items.filter((it) => {
            return it.id !== id
          })
        }).catch(failed)
      }).catch(() => {})

    },
    init() {
      client().request(`query list{
        listLeaveWord{
          id, body, createdAt
        }
      }`, {}).then((rst) => {
        this.items = rst.listLeaveWord
      }).catch(failed)
    },
    setPage(p) {
      this.page = p
    }
  }
}
</script>
