// dashboard/src/pages/admin/site/info.jsx
import React, {
  Component
} from 'react'
import {
  injectIntl,
  intlShape,
  FormattedMessage
} from 'react-intl'
import {
  Form,
  Input,
  message
} from 'antd'

import {
  Submit,
  formItemLayout
} from '../../../components/form'
import Card from '../../../components/layouts/Card'
import {
  client,
  failed
} from '../../../utils/request'
import Authorized from '../../../components/Authorized'
import {
  is_administrator
} from '../../../utils/authorized'

const FormItem = Form.Item

class Widget extends Component {
  handleSubmit = (e) => {
    const {
      formatMessage
    } = this.props.intl
    e.preventDefault()
    this.props.form.validateFields((err, values) => {
      if (!err) {
        client().request(`mutation form($title: String!, $subhead: String!, $keywords: String!, $description: String!, $copyright: String!){
            updateSiteInfo(title: $title, subhead: $subhead, keywords: $keywords, description: $description, copyright: $copyright) {
              createdAt
            }
          }`, values).then((rst) => {
          message.info(formatMessage({
            id: "flashes.success"
          }))
        }).catch(failed)
      }
    })
  }
  componentDidMount() {
    const {
      setFieldsValue
    } = this.props.form
    client().request(`query info{
        getSiteInfo{
          title, subhead, keywords, description, copyright
        }
      }`).then((rst) => {
      setFieldsValue(rst.getSiteInfo)
    }).catch(failed)
  }
  render() {
    const {
      formatMessage
    } = this.props.intl
    const {
      getFieldDecorator
    } = this.props.form
    return (<Authorized check={is_administrator}>
      <Card title={{
        id: "nut.users.profile.title"
      }}>
        <Form onSubmit={this.handleSubmit}>
          <FormItem {...formItemLayout} label={<FormattedMessage id = "nut.attributes.site.title" />} hasFeedback>
            {
              getFieldDecorator('title', {
                rules: [{
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }]
              })(<Input/>)
            }
          </FormItem>
          <FormItem {...formItemLayout} label={<FormattedMessage id = "nut.attributes.site.subhead" />} hasFeedback>
            {
              getFieldDecorator('subhead', {
                rules: [{
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }]
              })(<Input/>)
            }
          </FormItem>
          <FormItem {...formItemLayout} label={<FormattedMessage id = "nut.attributes.site.keywords" />} hasFeedback>
            {
              getFieldDecorator('keywords', {
                rules: [{
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }]
              })(<Input/>)
            }
          </FormItem>
          <FormItem {...formItemLayout} label={<FormattedMessage id = "nut.attributes.site.description" />} hasFeedback>
            {
              getFieldDecorator('description', {
                rules: [{
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }]
              })(<Input.TextArea rows={8}/>)
            }
          </FormItem>
          <FormItem {...formItemLayout} label={<FormattedMessage id = "nut.attributes.site.copyright" />} hasFeedback>
            {
              getFieldDecorator('copyright', {
                rules: [{
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }]
              })(<Input/>)
            }
          </FormItem>
          <Submit/>
        </Form>
      </Card>
    </Authorized>)
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired
}

export default Form.create()(injectIntl(Widget))

// desktop/src/plugins/nut/admin/site/Info.vue
<template>
<dashboard-layout :title="title" :role="role" :init="init">
  <col-form>
    <el-card :header="title">
      <el-form :rules="rules" ref="form" :model="form" label-width="80px">
        <el-form-item :label="$t('attributes.title')" prop="title">
          <el-input v-model="form.title" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.subhead')" prop="subhead">
          <el-input v-model="form.subhead" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.keywords')" prop="keywords">
          <el-input v-model="form.keywords" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.description')" prop="description">
          <el-input type="textarea" v-model="form.description" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.copyright')" prop="copyright">
          <el-input v-model="form.copyright" clearable required/>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t('buttons.submit')}}</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </col-form>
</dashboard-layout>
</template>

<script>
import {
  client,
  failed
} from '@/request'
import {
  ADMIN
} from '@/authorized'

export default {
  role: ADMIN,
  name: 'AdminSiteInfo',
  data() {
    return {
      title: this.$t("nut.admin.site.info.title"),
      form: {
        title: '',
        subhead: '',
        keywords: '',
        description: '',
        copyright: ''
      },
      rules: {
        title: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        subhead: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        keywords: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        description: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        copyright: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }]
      }
    }
  },
  methods: {
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          client().request(
            `mutation form($title: String!, $subhead: String!, $keywords: String!, $description: String!, $copyright: String!){
            updateSiteInfo(title: $title, subhead: $subhead, keywords: $keywords, description: $description, copyright: $copyright) {
              createdAt
            }
          }`,
            this.form).then(() => {
            this.$message({
              type: 'success',
              message: this.$t("flashes.success")
            })
          }).catch(failed)
        } else {
          return false;
        }
      });
    },
    init() {
      client().request(`query info{
        getSiteInfo{
          title, subhead, keywords, description, copyright
        }
      }`, {}).then((rst) => {
        this.form = rst.getSiteInfo
      }).catch(failed)
    }
  }
}
</script>
