// dashboard/src/pages/admin/site/seo.jsx
import React, {
  Component
} from 'react'
import {
  injectIntl,
  intlShape,
  FormattedMessage
} from 'react-intl'
import {
  Form,
  Input,
  Menu,
  message
} from 'antd'

import {
  Submit,
  formItemLayout
} from '../../../components/form'
import Card from '../../../components/layouts/Card'
import {
  client,
  failed
} from '../../../utils/request'
import Authorized from '../../../components/Authorized'
import {
  is_administrator
} from '../../../utils/authorized'

const FormItem = Form.Item

class Widget extends Component {
  constructor(props) {
    super(props)
    this.state = {
      languages: []
    }
  }
  handleMenuClick = (e) => {
    var win = window.open(e.key, '_blank')
    win.focus()
  }
  handleSubmit = (e) => {
    const {
      formatMessage
    } = this.props.intl
    e.preventDefault()
    this.props.form.validateFields((err, values) => {
      if (!err) {
        client().request(`mutation form($googleSiteVerifyCode: String!, $baiduSiteVerifyCode: String!){
            updateSiteSeo(googleSiteVerifyCode: $googleSiteVerifyCode, baiduSiteVerifyCode: $baiduSiteVerifyCode) {
              createdAt
            }
          }`, values).then((rst) => {
          message.info(formatMessage({
            id: "flashes.success"
          }))
        }).catch(failed)
      }
    })
  }
  componentDidMount() {
    const {
      setFieldsValue
    } = this.props.form
    client().request(`query info{
        getSiteSeo{
          googleSiteVerifyCode, baiduSiteVerifyCode
        }
        getSiteInfo{
          languages
        }
      }`).then((rst) => {
      setFieldsValue(rst.getSiteSeo)
      this.setState({
        languages: rst.getSiteInfo.languages
      })
    }).catch(() => {})
  }
  render() {
    const {
      formatMessage
    } = this.props.intl
    const {
      getFieldDecorator,
      getFieldValue
    } = this.props.form
    return (<Authorized check={is_administrator}>
      <Card title={{
        id: "nut.admin.site.seo.title"
      }}>
        <Form onSubmit={this.handleSubmit}>
          <FormItem {...formItemLayout} label={<FormattedMessage id = "nut.attributes.seo.google.site-verify-code" />} hasFeedback>
            {
              getFieldDecorator('googleSiteVerifyCode', {
                rules: [{
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }]
              })(<Input/>)
            }
          </FormItem>
          <FormItem {...formItemLayout} label={<FormattedMessage id = "nut.attributes.seo.baidu.site-verify-code" />} hasFeedback>
            {
              getFieldDecorator('baiduSiteVerifyCode', {
                rules: [{
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }]
              })(<Input/>)
            }
          </FormItem>
          <Submit/>
        </Form>
        <Menu mode="inline" onClick={this.handleMenuClick}>
          {this.state.languages.map((it)=>`/rss/${it}`).concat([
            '/robots.txt',
            '/sitemap.xml.gz',
            `/google${getFieldValue('googleSiteVerifyCode')}.html`,
            `/baidu_verify_${getFieldValue('baiduSiteVerifyCode')}.html`
          ]).map((it)=>(<Menu.Item key={it}>
            {it}
          </Menu.Item>))}
        </Menu>
      </Card>
    </Authorized>)
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired
}

export default Form.create()(injectIntl(Widget))

// desktop/src/plugins/nut/admin/site/Seo.vue
<template>
<dashboard-layout :title="title" :role="role" :init="init">
  <col-form>
    <el-card :header="title">
      <el-form :rules="rules" ref="form" :model="form" label-width="100px">
        <el-form-item :label="$t('nut.attributes.seo.google')" prop="google">
          <el-input v-model="form.google" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('nut.attributes.seo.baidu')" prop="baidu">
          <el-input v-model="form.baidu" clearable required/>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t('buttons.submit')}}</el-button>
        </el-form-item>
      </el-form>

      <el-menu @select="handleSelect">
        <el-menu-item :key="it" v-for="it in items" :index="it">
          <span slot="title">{{it}}</span>
        </el-menu-item>
      </el-menu>
    </el-card>
  </col-form>

</dashboard-layout>
</template>

<script>
import {
  client,
  failed
} from '@/request'
import {
  ADMIN
} from '@/authorized'
import locales from '@/locales'

export default {
  name: 'AdminSiteSeo',
  data() {
    return {
      role: {
        name: ADMIN
      },
      title: this.$t("nut.admin.site.seo.title"),
      form: {
        google: '',
        baidu: ''
      },
      rules: {}
    }
  },
  computed: {
    items() {
      return Object.keys(locales).map((it) => `/rss/${it}`).concat([
        `/google${this.form.google}.html`,
        `/baidu_verify_${this.form.baidu}.html`,
        '/robots.txt',
        '/sitemap.xml'
      ])
    }
  },
  methods: {
    handleSelect(key) {
      var win = window.open(key, '_blank')
      win.focus()
    },
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          client().request(
            `mutation form($google: String!, $baidu: String!){
            updateSiteSeo(google: $google, baidu: $baidu) {
              createdAt
            }
          }`,
            this.form).then(() => {
            this.$message({
              type: 'success',
              message: this.$t("flashes.success")
            })
          }).catch(failed)
        } else {
          return false;
        }
      });
    },
    init() {
      client().request(`query info{
        getSiteSeo{
          google, baidu
        }
      }`, {}).then((rst) => {
        this.form = rst.getSiteSeo
      }).catch(() => {})
    }
  }
}
</script>
