// dashboard/src/plugins/nut/admin/site/Seo.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import {
  Form,
  Row,
  Col,
  Input,
  Card,
  message
} from 'antd'
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import {connect} from 'react-redux'
import {push} from 'react-router-redux'

import Layout from '../../../../layouts/dashboard'
import {ADMIN} from '../../../../auth'
import {post, get} from '../../../../ajax'
import {Submit, formItemLayout} from '../../../../components/form'

const FormItem = Form.Item

class Widget extends Component {
  state = {
    item: {}
  }
  componentDidMount() {
    const {setFieldsValue} = this.props.form
    get('/admin/site/seo').then((rst) => {
      setFieldsValue(rst)
      this.setState({item: rst})
    }).catch(message.error)
  }
  handleSubmit = (e) => {
    const {formatMessage} = this.props.intl
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        post('/admin/site/seo', values).then(() => {
          message.success(formatMessage({id: "flash.success"}))
        }).catch(message.error);
      }
    });
  }
  render() {
    const {formatMessage} = this.props.intl
    const {getFieldDecorator} = this.props.form
    const title = {
      id: "nut.admin.site.seo.title"
    }
    return (<Layout breads={[{
          href: "/admin/site/seo",
          label: title
        }
      ]} title={title} roles={[ADMIN]}>
      <Row>
        <Col md={{
            span: 12,
            offset: 2
          }}>
          <Form onSubmit={this.handleSubmit}>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "nut.admin.site.seo.googleVerifyCode" />} hasFeedback={true}>
              {
                getFieldDecorator('googleVerifyCode', {
                  rules: [
                    {
                      required: true,
                      message: formatMessage({id: "validator.required"})
                    }
                  ]
                })(<Input/>)
              }
            </FormItem>
            <Submit/>
          </Form>
        </Col>
      </Row>
      <Row>
        <Col md={{
            span: 6,
            offset: 4
          }}>
          <Card>
            {
              [`/google${this.state.item.googleVerifyCode}.html`, '/robots.txt', '/sitemap.xml.gz'].concat(this.props.site.languages.map(it => `/rss/${it}`)).map((it, id) => (<p key={id}>
                <a href={it} target='_blank'>{it}</a>
              </p>))
            }
          </Card>
        </Col>
      </Row>
    </Layout>);
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired,
  site: PropTypes.object.isRequired,
  push: PropTypes.func.isRequired
}

const WidgetF = Form.create()(injectIntl(Widget))

export default connect(state => ({site: state.siteInfo}), {
  push
},)(WidgetF)

// desktop/src/plugins/nut/admin/site/Seo.vue
<template>
<dashboard-layout :title="title" :role="role" :init="init">
  <col-form>
    <el-card :header="title">
      <el-form :rules="rules" ref="form" :model="form" label-width="100px">
        <el-form-item :label="$t('nut.attributes.seo.google')" prop="google">
          <el-input v-model="form.google" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('nut.attributes.seo.baidu')" prop="baidu">
          <el-input v-model="form.baidu" clearable required/>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t('buttons.submit')}}</el-button>
        </el-form-item>
      </el-form>

      <el-menu @select="handleSelect">
        <el-menu-item :key="it" v-for="it in items" :index="it">
          <span slot="title">{{it}}</span>
        </el-menu-item>
      </el-menu>
    </el-card>
  </col-form>

</dashboard-layout>
</template>

<script>
import {
  client,
  failed
} from '@/request'
import {
  ADMIN
} from '@/authorized'
import locales from '@/locales'

export default {
  name: 'AdminSiteSeo',
  data() {
    return {
      role: {
        name: ADMIN
      },
      title: this.$t("nut.admin.site.seo.title"),
      form: {
        google: '',
        baidu: ''
      },
      rules: {}
    }
  },
  computed: {
    items() {
      return Object.keys(locales).map((it) => `/rss/${it}`).concat([
        `/google${this.form.google}.html`,
        `/baidu_verify_${this.form.baidu}.html`,
        '/robots.txt',
        '/sitemap.xml'
      ])
    }
  },
  methods: {
    handleSelect(key) {
      var win = window.open(key, '_blank')
      win.focus()
    },
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          client().request(
            `mutation form($google: String!, $baidu: String!){
            updateSiteSeo(google: $google, baidu: $baidu) {
              createdAt
            }
          }`,
            this.form).then(() => {
            this.$message({
              type: 'success',
              message: this.$t("flashes.success")
            })
          }).catch(failed)
        } else {
          return false;
        }
      });
    },
    init() {
      client().request(`query info{
        getSiteSeo{
          google, baidu
        }
      }`, {}).then((rst) => {
        this.form = rst.getSiteSeo
      }).catch(() => {})
    }
  }
}
</script>
