// dashboard/src/pages/admin/site/smtp.jsx
import React, {
  Component
} from 'react'
import {
  injectIntl,
  intlShape,
  FormattedMessage
} from 'react-intl'
import {
  Form,
  Input,
  Select,
  message
} from 'antd'

import {
  Submit,
  formItemLayout
} from '../../../components/form'
import Card from '../../../components/layouts/Card'
import {
  client,
  failed
} from '../../../utils/request'
import Authorized from '../../../components/Authorized'
import {
  is_administrator
} from '../../../utils/authorized'

const FormItem = Form.Item

class Widget extends Component {
  handleSubmit = (e) => {
    const {
      formatMessage
    } = this.props.intl
    e.preventDefault()
    this.props.form.validateFields((err, values) => {
      if (!err) {
        client().request(`mutation form($host: String!, $port: Int!, $user: String!, $password: String!){
            updateSiteSmtp(host: $host, port: $port, user: $user, password: $password) {
              createdAt
            }
          }`, values).then((rst) => {
          message.info(formatMessage({
            id: "flashes.success"
          }))
        }).catch(failed)
      }
    })
  }
  checkPassword = (rule, value, callback) => {
    const {
      formatMessage
    } = this.props.intl
    const {
      getFieldValue
    } = this.props.form
    if (value && value !== getFieldValue('password')) {
      callback(formatMessage({
        id: "validations.password-confirmation"
      }));
    } else {
      callback();
    }
  }
  componentDidMount() {
    const {
      setFieldsValue
    } = this.props.form
    client().request(`query info{
        getSiteSmtp{
          host, port, user, password
        }
      }`).then((rst) => {
      setFieldsValue(Object.assign(rst.getSiteSmtp, {
        passwordConfirmation: ''
      }))
    }).catch(() => {
      setFieldsValue({
        port: 25
      })
    })
  }
  render() {
    const {
      formatMessage
    } = this.props.intl
    const {
      getFieldDecorator
    } = this.props.form

    return (<Authorized check={is_administrator}>
      <Card title={{
        id: "nut.admin.site.smtp.title"
      }}>
        <Form onSubmit={this.handleSubmit}>
          <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.host" />} hasFeedback>
            {
              getFieldDecorator('host', {
                rules: [{
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }]
              })(<Input/>)
            }
          </FormItem>
          <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.port" />} hasFeedback>
            {
              getFieldDecorator('port', {
                rules: []
              })(<Select>
                {[25, 465, 587].map((it)=>(<Select.Option key={it} value={it}>{it}</Select.Option>))}
              </Select>)
            }
          </FormItem>
          <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.user" />} hasFeedback={true}>
            {
              getFieldDecorator('user', {
                rules: [{
                  type: 'email',
                  message: formatMessage({id: "validations.email"})
                }, {
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }]
              })(<Input/>)
            }
          </FormItem>
          <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.password" />} hasFeedback={true}>
            {
              getFieldDecorator('password', {
                rules: [
                {
                    required: true,
                    max: 30,
                    min: 6,
                  message: formatMessage({id: "validations.password"})
                }
                ]
              })(<Input type="password"/>)
            }
          </FormItem>
          <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.password-confirmation" />} hasFeedback={true}>
            {
              getFieldDecorator('passwordConfirmation', {
                rules: [
                {
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }, {
                  validator: this.checkPassword
                }]
              })(<Input type="password"/>)
            }
          </FormItem>
          <Submit/>
        </Form>
      </Card>
    </Authorized>)
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired
}

export default Form.create()(injectIntl(Widget))

// desktop/src/plugins/nut/admin/site/Smtp.vue
<template>
<dashboard-layout :title="title" :role="role" :init="init">
  <col-form>
    <el-card :header="title">
      <el-form :rules="rules" ref="form" :model="form" label-width="80px">
        <el-form-item :label="$t('attributes.host')" prop="host">
          <el-input v-model="form.host" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.port')">
          <el-select v-model="form.port">
            <el-option v-for="it in [25, 465, 587]" :key="it" :label="it" :value="it" />
          </el-select>
        </el-form-item>
        <el-form-item :label="$t('nut.attributes.smtp.user')" prop="user">
          <el-input v-model="form.user" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.password')" prop="password">
          <el-input type="password" v-model="form.password" clearable auto-complete="off" />
        </el-form-item>
        <el-form-item :label="$t('attributes.password-confirmation')" prop="passwordConfirmation">
          <el-input type="password" v-model="form.passwordConfirmation" clearable auto-complete="off" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t('buttons.submit')}}</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </col-form>
</dashboard-layout>
</template>

<script>
import {
  client,
  failed
} from '@/request'
import {
  ADMIN
} from '@/authorized'

export default {
  name: 'AdminSiteAuthor',
  data() {
    var validatePasswords = (rule, value, callback) => {
      if (value === '' || value !== this.form.password) {
        callback(new Error(this.$t('validations.password-confirmation')));
      } else {
        callback();
      }
    };

    return {
      role: {
        name: ADMIN
      },
      title: this.$t("nut.admin.site.smtp.title"),
      form: {
        host: '',
        port: 25,
        user: '',
        password: '',
        passwordConfirmation: ''
      },
      rules: {
        host: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        user: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }, {
          type: 'email',
          message: this.$t('validations.email'),
          trigger: ['blur', 'change']
        }],
        password: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }, {
          min: 6,
          max: 32,
          message: this.$t('validations.password'),
          trigger: ['blur', 'change']
        }],
        passwordConfirmation: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }, {
          validator: validatePasswords,
          trigger: ['blur', 'change']
        }]
      }
    }
  },
  methods: {
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          client().request(
            `mutation form($host: String!, $port: Int!, $user: String!, $password: String!){
            updateSiteSmtp(host: $host, port: $port, user: $user, password: $password) {
              createdAt
            }
          }`,
            this.form).then(() => {
            this.$message({
              type: 'success',
              message: this.$t("flashes.success")
            })
          }).catch(failed)
        } else {
          return false;
        }
      });
    },
    init() {
      client().request(`query info{
        getSiteSmtp{
          host, port, user, password
        }
      }`, {}).then((rst) => {
        this.form = Object.assign({
          passwordConfirmation: ''
        }, rst.getSiteSmtp)
      }).catch(() => {})
    }
  }
}
</script>
