// desktop/src/plugins/nut/users/ChangePassword.vue
<template>
<dashboard-layout :title="title" :role="null">
  <col-form>
    <el-card :header="title">
      <el-form :rules="rules" ref="form" :model="form" label-width="80px">
        <el-form-item :label="$t('attributes.current-password')" prop="currentPassword">
          <el-input type="password" v-model="form.currentPassword" clearable auto-complete="off" />
        </el-form-item>
        <el-form-item :label="$t('attributes.new-password')" prop="newPassword">
          <el-input type="password" v-model="form.newPassword" clearable auto-complete="off" />
        </el-form-item>
        <el-form-item :label="$t('attributes.password-confirmation')" prop="passwordConfirmation">
          <el-input type="password" v-model="form.passwordConfirmation" clearable auto-complete="off" />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t('buttons.submit')}}</el-button>
          <el-button @click="resetForm('form')">{{$t('buttons.reset')}}</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </col-form>
</dashboard-layout>
</template>

<script>
import {
  client,
  failed
} from '@/request'

export default {
  name: 'UsersChangePassword',
  data() {
    var validatePasswords = (rule, value, callback) => {
      if (value === '' || value !== this.form.newPassword) {
        callback(new Error(this.$t('validations.password-confirmation')));
      } else {
        callback();
      }
    };
    return {
      title: this.$t("nut.users.change-password.title"),
      form: {
        currentPassword: '',
        newPassword: '',
        passwordConfirmation: ''
      },
      rules: {
        currentPassword: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        newPassword: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }, {
          min: 6,
          max: 32,
          message: this.$t('validations.password'),
          trigger: ['blur', 'change']
        }],
        passwordConfirmation: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }, {
          validator: validatePasswords,
          trigger: ['blur', 'change']
        }]
      }
    }
  },
  methods: {
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          client().request(`mutation form($currentPassword: String!, $newPassword: String!){
            changeUserPassword(currentPassword: $currentPassword, newPassword: $newPassword) {
              createdAt
            }
          }`, {
            currentPassword: this.form.currentPassword,
            newPassword: this.form.newPassword
          }).then(() => {
            this.$message({
              type: 'success',
              message: this.$t("flashes.success")
            })
            this.$refs[formName].resetFields();
          }).catch(failed)
        } else {
          return false;
        }
      });
    },
    resetForm(formName) {
      this.$refs[formName].resetFields();
    }
  }
}
</script>

// dashboard/src/plugins/nut/users/ChangePassword.jsx
import React, {Component} from 'react'
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import {connect} from 'react-redux'
import {Form, Input, message} from 'antd'

import {Submit, formItemLayout} from '../../components/form'
import {client, USERS_CHANGE_PASSWORD, failed} from '../../request'
import Card from '../../components/Card'

const FormItem = Form.Item

class Widget extends Component {
  handleSubmit = (e) => {
    const {formatMessage} = this.props.intl
    e.preventDefault()
    this.props.form.validateFields((err, values) => {
      if (!err) {
        client().request(USERS_CHANGE_PASSWORD, {
          currentPassword: values.currentPassword,
          newPassword: values.newPassword
        }).then((rst) => {
          message.info(formatMessage({id: "flashes.success"}))
        }).catch(failed)
      }
    })
  }
  checkPassword = (rule, value, callback) => {
    const {formatMessage} = this.props.intl
    const {getFieldValue} = this.props.form
    if (value && value !== getFieldValue('newPassword')) {
      callback(formatMessage({id: "validations.password-confirmation"}));
    } else {
      callback();
    }
  }
  render() {
    const {formatMessage} = this.props.intl
    const {getFieldDecorator} = this.props.form

    return (<Card title={{
        id: "nut.users.change-password.title"
      }}>
      <Form onSubmit={this.handleSubmit}>
        <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.current-password" />} hasFeedback={true}>
          {
            getFieldDecorator('currentPassword', {
              rules: [
                {
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }
              ]
            })(<Input type="password"/>)
          }
        </FormItem>
        <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.new-password" />} hasFeedback={true}>
          {
            getFieldDecorator('newPassword', {
              rules: [
                {
                  required: true,
                  max: 30,
                  min: 6,
                  message: formatMessage({id: "validations.password"})
                }
              ]
            })(<Input type="password"/>)
          }
        </FormItem>
        <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.password-confirmation" />} hasFeedback={true}>
          {
            getFieldDecorator('passwordConfirmation', {
              rules: [
                {
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }, {
                  validator: this.checkPassword
                }
              ]
            })(<Input type="password"/>)
          }
        </FormItem>
        <Submit/>
      </Form>
    </Card>)
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired
}

export default connect(state => ({}), {})(Form.create()(injectIntl(Widget)))
