// by-vue/src/plugins/nut/leave-words/New.vue
<template>
<application-layout :title="$t('leave-words.new.title')" :on-submit="onSubmit">
  <v-textarea prepend-icon="feedback" :label="$t('attributes.content')" />
</application-layout>
</template>


<script>
export default {
  name: 'NewLeaveWord',
  methods: {
    onSubmit: function(event) {
      event.preventDefault()
      console.log('leave words new')
    }
  }
}
</script>

// dashboard/src/routes/leave-words/New.jsx
import React, {
  Component
} from 'react'

import Application from '../../layouts/Application'

class Widget extends Component {
  handleSubmit = (e) => {
    e.preventDefault();
    console.log('aaa')
  }
  render() {
    return (<Application title="nut.leave-words.new.title" submit={this.handleSubmit}>
      leave-words.new
    </Application>);
  }
}

export default Widget;
