// desktop/src/plugins/nut/admin/links/Form.vue
<template>
<dashboard-layout :title="title" :role="null" :init="init">
  <col-form>
    <el-card :header="title">
      <el-form :rules="rules" ref="form" :model="form" label-width="80px">
        <el-form-item :label="$t('attributes.name')" prop="label">
          <el-input v-model="form.label" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.url')" prop="href">
          <el-input v-model="form.href" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.loc')">
          <el-select v-model="form.loc">
            <el-option v-for="it in ['header', 'footer', 'sider']" :key="it" :label="it" :value="it" />
          </el-select>
        </el-form-item>
        <el-form-item :label="$t('attributes.x')">
          <el-select v-model="form.x">
            <el-option v-for="it in sort_orders" :key="it" :label="it" :value="it" />
          </el-select>
        </el-form-item>
        <el-form-item :label="$t('attributes.y')">
          <el-select v-model="form.y">
            <el-option v-for="it in sort_orders" :key="it" :label="it" :value="it" />
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t('buttons.submit')}}</el-button>
          <el-button @click="go_back">{{$t('buttons.return')}}</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </col-form>
</dashboard-layout>
</template>

<script>
import {
  client,
  failed
} from '@/request'
import lodash from 'lodash'

export default {
  name: 'AdminLinksForm',
  data() {
    return {
      title: this.$t("nut.admin.links.index.title"),
      form: {
        id: null,
        label: '',
        href: '',
        loc: 'header',
        x: 0,
        y: 0,
      },
      rules: {
        label: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        href: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }]
      }
    }
  },
  computed: {
    sort_orders() {
      return lodash.range(-9, 10)
    }
  },
  methods: {
    go_back() {
      this.$router.push({
        name: 'admin.links.index'
      })
    },
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          var id = this.$route.params.id
          client().request(id ?
            `mutation form($id: String!, $label: String!, $href: String!, $loc: String!, $x: Int!, $y: Int!){
            updateLink(id: $id, label: $label, href: $href, loc: $loc, x: $x, y: $y) {
              createdAt
            }
          }` :
            `mutation form($label: String!, $href: String!, $loc: String!, $x: Int!, $y: Int!){
            createLink(label: $label, href: $href, loc: $loc, x: $x, y: $y) {
              createdAt
            }
          }`,
            this.form).then(() => {
            this.$message({
              type: 'success',
              message: this.$t("flashes.success")
            })
            this.go_back()
          }).catch(failed)
        } else {
          return false;
        }
      });
    },
    init() {
      var id = this.$route.params.id
      if (id) {
        client().request(`query info($id: String!){
        showLink(id: $id) {
          id, label, href, loc, x, y
        }
      }`, {
          id
        }).then((rst) => {
          this.form = rst.showLink
        }).catch(failed)
      }
    }
  }
}
</script>

// old/src-old/ds/src/plugins/nut/admin/links/Form.jsx
import React, {Component} from 'react'
import PropTypes from 'prop-types'
import {
  Form,
  Row,
  Col,
  Input,
  Select,
  message
} from 'antd'
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import {connect} from 'react-redux'
import {push} from 'react-router-redux'

import Layout from '../../../../layouts/dashboard'
import {post, get} from '../../../../ajax'
import {Submit, orders, formItemLayout} from '../../../../components/form'
import {ADMIN} from '../../../../auth'

const FormItem = Form.Item
const Option = Select.Option

class Widget extends Component {
  componentDidMount() {
    const {setFieldsValue} = this.props.form
    const {id} = this.props.match.params
    if (id) {
      get(`/admin/links/${id}`).then((rst) => setFieldsValue({label: rst.label, href: rst.href, x: rst.x.toString(), y: rst.y.toString(), loc: rst.loc})).catch(message.error)
    } else {
      setFieldsValue({x: '0', y: '0', loc: 'header'})
    }
  }
  handleSubmit = (e) => {
    const {formatMessage} = this.props.intl
    const {push} = this.props
    const {id} = this.props.match.params
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        post(
          id
          ? `/admin/links/${id}`
          : '/admin/links',
        Object.assign({}, values, {
          x: parseInt(values.x, 10),
          y: parseInt(values.y, 10)
        })).then(() => {
          message.success(formatMessage({id: "flash.success"}))
          push('/admin/links')
        }).catch(message.error);
      }
    });
  }
  render() {
    const {formatMessage} = this.props.intl
    const {getFieldDecorator} = this.props.form
    const {id} = this.props.match.params
    const title = id
      ? {
        id: "buttons.edit",
        values: {
          id: id
        }
      }
      : {
        id: "buttons.new"
      }
    return (<Layout breads={[
        {
          href: '/admin/links',
          label: {
            id: 'nut.admin.links.index.title'
          }
        },
        id
          ? {
            href: `/admin/links/edit/${id}`,
            label: title
          }
          : {
            href: "/admin/links/new",
            label: title
          }
      ]} title={title} roles={[ADMIN]}>
      <Row>
        <Col md={{
            span: 12,
            offset: 2
          }}>
          <Form onSubmit={this.handleSubmit}>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.loc" />}>
              {
                getFieldDecorator('loc')(<Select>
                  {['header', 'footer', 'sidebar'].map((p) => (<Option key={p} value={p}>{p}</Option>))}
                </Select>)
              }
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.x" />}>
              {
                getFieldDecorator('x')(<Select>
                  {orders(10).map((p) => (<Option key={p} value={p}>{p}</Option>))}
                </Select>)
              }
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.y" />}>
              {
                getFieldDecorator('y')(<Select>
                  {orders(10).map((p) => (<Option key={p} value={p}>{p}</Option>))}
                </Select>)
              }
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.label" />} hasFeedback={true}>
              {
                getFieldDecorator('label', {
                  rules: [
                    {
                      required: true,
                      message: formatMessage({id: "validator.required"})
                    }
                  ]
                })(<Input/>)
              }
            </FormItem>
            <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.href" />} hasFeedback={true}>
              {
                getFieldDecorator('href', {
                  rules: [
                    {
                      required: true,
                      message: formatMessage({id: "validator.required"})
                    }
                  ]
                })(<Input/>)
              }
            </FormItem>
            <Submit/>
          </Form>
        </Col>
      </Row>
    </Layout>);
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired,
  push: PropTypes.func.isRequired
}

const WidgetF = Form.create()(injectIntl(Widget))

export default connect(state => ({}), {
  push
},)(WidgetF)
