// dashboard/src/components/users/EmailForm.jsx
import React, {
  Component
} from 'react'
import PropTypes from 'prop-types'
import router from 'umi/router'
import {
  injectIntl,
  intlShape,
  FormattedMessage
} from 'react-intl'
import {
  Form,
  Input,
  message
} from 'antd'

import Layout from '../layouts/UsersSharedLinks'
import {
  Submit,
  formItemLayout
} from '../form'
import {
  client,
  failed
} from '../../utils/request'

const FormItem = Form.Item

class Widget extends Component {
  handleSubmit = (e) => {
    const {
      action,
      query
    } = this.props
    const {
      formatMessage
    } = this.props.intl
    e.preventDefault()
    this.props.form.validateFields((err, values) => {
      if (!err) {
        client().request(query, values).then((rst) => {
          message.info(formatMessage({
            id: `nut.users.${action}.success`
          }))
          router.push('/users/sign-in')
        }).catch(failed)
      }
    })
  }
  render() {
    const {
      action
    } = this.props
    const {
      formatMessage
    } = this.props.intl
    const {
      getFieldDecorator
    } = this.props.form
    return (<Layout title={`nut.users.${action}.title`}>
      <Form onSubmit={this.handleSubmit}>
        <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.email" />} hasFeedback={true}>
          {
            getFieldDecorator('email', {
              rules: [
              {
                  type: 'email',
                message: formatMessage({id: "validations.email"})
              }, {
                  required: true,
                message: formatMessage({id: "validations.required"})
              }
              ]
            })(<Input/>)
          }
        </FormItem>
        <Submit/>
      </Form>
    </Layout>);
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired,
  action: PropTypes.string.isRequired,
  query: PropTypes.string.isRequired
}

export default Form.create()(injectIntl(Widget))

// desktop/src/plugins/nut/users/EmailForm.vue
<template>
<application-layout :title="title">
  <el-card :header="title">
    <el-form :rules="rules" ref="form" :model="form" label-width="80px">
      <el-form-item :label="$t('attributes.email')" prop="email">
        <el-input v-model="form.email" clearable required/>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="submitForm('form')">{{$t('buttons.submit')}}</el-button>
        <el-button @click="resetForm('form')">{{$t('buttons.reset')}}</el-button>
      </el-form-item>
    </el-form>
    <shared-links />
  </el-card>
</application-layout>
</template>

<script>
import SharedLinks from './SharedLinks'
import {
  client,
  failed
} from '@/request'

export default {
  name: 'UsersEmailForm',
  components: {
    'shared-links': SharedLinks
  },
  props: {
    action: String,
    query: String,
  },
  data() {
    return {
      title: this.$t(`nut.users.${this.action}.title`),
      form: {
        email: ''
      },
      rules: {
        email: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }, {
          type: 'email',
          message: this.$t('validations.email'),
          trigger: ['blur', 'change']
        }],
      }
    }
  },
  methods: {
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          client().request(this.query, {
            email: this.form.email
          }).then(() => {
            this.$message({
              type: 'success',
              message: this.$t(`nut.users.${this.action}.success`)
            })
            this.$router.push({
              name: 'users.sign-in'
            })
          }).catch(failed)
        } else {
          return false;
        }
      });
    },
    resetForm(formName) {
      this.$refs[formName].resetFields();
    }
  }
}
</script>
