// dashboard/src/pages/users/Profile.jsx
import React, {Component} from 'react'
import {injectIntl, intlShape, FormattedMessage} from 'react-intl'
import {connect} from 'react-redux'
import {Form, Input, message} from 'antd'

import {Submit, formItemLayout} from '../../components/form'
import Card from '../../components/Card'
import {client, USERS_PROFILE_GET, USERS_PROFILE_SET, failed} from '../../request'

const FormItem = Form.Item

class Widget extends Component {
  handleSubmit = (e) => {
    const {formatMessage} = this.props.intl
    e.preventDefault()
    this.props.form.validateFields((err, values) => {
      if (!err) {
        client().request(USERS_PROFILE_SET, {
          logo: values.logo,
          name: values.name
        }).then((rst) => {
          message.info(formatMessage({id: "flashes.success"}))
        }).catch(failed)
      }
    })
  }
  componentDidMount() {
    const {setFieldsValue} = this.props.form
    client().request(USERS_PROFILE_GET).then((rst) => {
      setFieldsValue(rst.getUserProfile)
    }).catch(failed)
  }
  render() {
    const {formatMessage} = this.props.intl
    const {getFieldDecorator} = this.props.form
    return (<Card title={{
        id: "nut.users.profile.title"
      }}>
      <Form onSubmit={this.handleSubmit}>
        <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.username" />} hasFeedback={true}>
          {
            getFieldDecorator('name', {
              rules: [
                {
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }
              ]
            })(<Input/>)
          }
        </FormItem>
        <FormItem {...formItemLayout} label={<FormattedMessage id = "attributes.email" />} hasFeedback={true}>
          {
            getFieldDecorator('email', {
              rules: [
                {
                  type: 'email',
                  message: formatMessage({id: "validations.email"})
                }, {
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }
              ]
            })(<Input disabled={true}/>)
          }
        </FormItem>
        <FormItem {...formItemLayout} label={<FormattedMessage id = "nut.attributes.user.logo" />} hasFeedback={true}>
          {
            getFieldDecorator('logo', {
              rules: [
                {
                  required: true,
                  message: formatMessage({id: "validations.required"})
                }
              ]
            })(<Input/>)
          }
        </FormItem>
        <Submit/>
      </Form>
    </Card>)
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired
}

export default connect(state => ({}), {})(Form.create()(injectIntl(Widget)))

// desktop/src/plugins/nut/users/Profile.vue
<template>
<dashboard-layout :title="title" :role="null" :init="init">
  <col-form>
    <el-card :header="title">
      <el-form :rules="rules" ref="form" :model="form" label-width="80px">
        <el-form-item :label="$t('attributes.email')" prop="email">
          <el-input v-model="form.email" disabled clearable required/>
        </el-form-item>
        <el-form-item :label="$t('attributes.username')" prop="name">
          <el-input v-model="form.name" clearable required/>
        </el-form-item>
        <el-form-item :label="$t('nut.attributes.user.logo')" prop="logo">
          <el-input v-model="form.logo" clearable required/>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="submitForm('form')">{{$t('buttons.submit')}}</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </col-form>
</dashboard-layout>
</template>

<script>
import {
  client,
  failed
} from '@/request'

export default {
  name: 'UsersProfile',
  data() {
    return {
      title: this.$t("nut.users.profile.title"),
      form: {
        email: '',
        name: '',
        logo: ''
      },
      rules: {
        name: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }],
        logo: [{
          required: true,
          message: this.$t('validations.required'),
          trigger: ['blur', 'change']
        }]
      }
    }
  },
  methods: {
    submitForm(formName) {
      this.$refs[formName].validate((valid) => {
        if (valid) {
          client().request(`mutation info($name: String!, $logo: String!){
            updateUserProfile(name: $name, logo: $logo) {
              createdAt
            }
          }`, {
            name: this.form.name,
            logo: this.form.logo
          }).then(() => {
            this.$message({
              type: 'success',
              message: this.$t("flashes.success")
            })
          }).catch(failed)
        } else {
          return false;
        }
      });
    },
    init() {
      client().request(`query info{
        getUserProfile {
          name,
          logo,
          email
        }
      }`, {}).then((rst) => {
        var ifo = rst.getUserProfile
        this.form.name = ifo.name
        this.form.logo = ifo.logo
        this.form.email = ifo.email
      }).catch(failed)
    }
  }
}
</script>
