// dashboard/src/components/users/TokenForm.jsx
import React, {
  Component
} from 'react'
import PropTypes from 'prop-types'
import router from 'umi/router'
import {
  injectIntl,
  intlShape
} from 'react-intl'
import {
  message
} from 'antd'
import withRouter from 'umi/withRouter'

import {
  client,
  failed
} from '../../utils/request'

class Widget extends Component {
  componentDidMount() {
    const {
      action,
      query,
      match
    } = this.props
    const {
      formatMessage
    } = this.props.intl

    client().request(query, match.params).then((rst) => {
      message.info(formatMessage({
        id: `nut.emails.user.${action}.success`
      }))
      router.push('/users/sign-in')
    }).catch(failed)
  }
  render() {
    return (<div/>);
  }
}

Widget.propTypes = {
  intl: intlShape.isRequired,
  action: PropTypes.string.isRequired,
  query: PropTypes.string.isRequired
}

export default withRouter(injectIntl(Widget))

// desktop/src/plugins/nut/users/TokenForm.vue
<template>
<div v-loading="loading" />
</template>

<script>
import {
  client,
  failed
} from '@/request'

export default {
  name: 'UsersTokenForm',
  props: {
    action: String,
    query: String,
  },
  created() {
    client().request(this.query, {
      token: this.$route.params.token
    }).then(() => {
      this.$message({
        type: 'success',
        message: this.$t(`nut.users.${this.action}.token.success`)
      })
      this.$router.push({
        name: 'users.sign-in'
      })
    }).catch(failed)
  },
  data() {
    return {
      loading: true
    }
  }
}
</script>
